# Generated by Django 4.2.3 on 2023-08-11 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='none', max_length=15)),
                ('price', models.FloatField()),
                ('title', models.CharField(max_length=100)),
                ('region', models.CharField(default='none', max_length=25)),
                ('city', models.CharField(default='none', max_length=25)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('date', models.DateField(default=datetime.datetime(2023, 8, 11, 10, 59, 18, 261124))),
                ('size', models.CharField(blank=True, default='none', max_length=50)),
                ('contact', models.CharField(blank=True, max_length=10)),
                ('dp', models.ImageField(blank=True, default='default.jpg', upload_to='images/')),
                ('pic1', models.ImageField(blank=True, default='default.jpg', upload_to='images/')),
                ('pic2', models.ImageField(blank=True, default='default.jpg', upload_to='images/')),
                ('pic3', models.ImageField(blank=True, default='default.jpg', upload_to='images/')),
                ('pic4', models.ImageField(blank=True, default='default.jpg', upload_to='images/')),
                ('pic5', models.ImageField(blank=True, default='default.jpg', upload_to='images/')),
                ('pic6', models.ImageField(blank=True, default='default.jpg', upload_to='images/')),
                ('rooms', models.FloatField(max_length=50)),
                ('bathrooms', models.FloatField(max_length=50)),
                ('utilities', models.CharField(max_length=100)),
                ('category', models.CharField(default='none', max_length=100)),
                ('active', models.CharField(blank=True, default='0', max_length=10)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('newsletter', models.CharField(default=0, max_length=100)),
                ('document_a', models.FloatField(default=0, max_length=100)),
                ('document_b', models.FloatField(default=0, max_length=100)),
                ('document_c', models.FloatField(default=0, max_length=100)),
                ('availability_from', models.DateField(default=datetime.datetime(2023, 8, 11, 10, 59, 18, 261124), max_length=100)),
                ('availability_to', models.DateField(default=datetime.datetime(2023, 8, 11, 10, 59, 18, 261124), max_length=100)),
            ],
        ),
    ]
