# Generated by Django 4.2.3 on 2023-08-09 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tofiee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bathrooms',
            field=models.FloatField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='category',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.CharField(default='none', max_length=25),
        ),
        migrations.AddField(
            model_name='member',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='member',
            name='document_a',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='dp',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='member',
            name='newsletter',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='pic1',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='member',
            name='pic2',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='member',
            name='pic3',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='member',
            name='pic4',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='member',
            name='pic5',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='member',
            name='pic6',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='member',
            name='region',
            field=models.CharField(default='none', max_length=25),
        ),
        migrations.AddField(
            model_name='member',
            name='rooms',
            field=models.FloatField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='slug',
            field=models.SlugField(default=0, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='utilities',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='active',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='contact',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 13, 42, 35, 554879)),
        ),
        migrations.AlterField(
            model_name='member',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='size',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='title',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(default='none', max_length=15),
        ),
    ]
