# Generated by Django 4.2.3 on 2023-08-11 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tofiee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='availability_from',
            field=models.DateField(default=datetime.datetime(2023, 8, 11, 11, 3, 44, 881972), max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='availability_to',
            field=models.DateField(default=datetime.datetime(2023, 8, 11, 11, 3, 44, 881972), max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 11, 11, 3, 44, 881972)),
        ),
    ]
