# Generated by Django 4.2.3 on 2023-08-09 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tofiee', '0002_member_bathrooms_member_category_member_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='document_b',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='document_c',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 14, 50, 40, 304700)),
        ),
    ]
